spring:
  sql:
    init:
      mode: never
  jpa:
    defer-datasource-initialization: false
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show-sql: false
        format_sql: false
  mail:
    properties:
      "mail.debug": false
