spring:
  host: ${HOST}
  application:
    name: eduVirt
  jpa:
    open-in-view: false
  profiles:
    active: @spring.profiles.active@

jdbc:
  eduvirt:
    driver-class-name: ${EDUVIRT_DB_DRIVER_CLASS}
    username: ${EDUVIRT_DB_USERNAME}
    password: ${EDUVIRT_DB_PASSWORD}
    jdbcUrl: ${EDUVIRT_DB_URL}
    maximum-pool-size: ${EDUVIRT_DB_MAX_POOL_SIZE}
    maxWaitMillis: ${EDUVIRT_DB_MAX_LIFETIME}
  ovirt:
    driver-class-name: ${OVIRT_DB_DRIVER_CLASS}
    username: ${OVIRT_DB_USERNAME}
    password: ${OVIRT_DB_PASSWORD}
    jdbcUrl: ${OVIRT_DB_URL}
    readOnly: true
    maximum-pool-size: ${OVIRT_DB_MAX_POOL_SIZE}
    maxWaitMillis: ${OVIRT_DB_MAX_LIFETIME}

ovirt:
  engine:
    url: ${ENGINE_URL}
    username: ${ENGINE_USERNAME}
    password: ${ENGINE_PASSWORD}
    jks:
      file: ${JKS_FILE}
      password: ${JKS_PASSWORD}

auth:
  secret-key: ${AUTH_SECRET_KEY}
  expiration-hours: ${AUTH_EXPIRATION_HOURS}
  keycloack:
    tokenUri: ${KEYCLOAK_TOKEN_URI}
    url: ${KEYCLOAK_URL}
    clientId: ${KEYCLOAK_CLIENT_ID}
    clientSecret: ${KEYCLOAK_CLIENT_SECRET}
    redirectUri: ${KEYCLOAK_REDIRECT_URI}
