spring:
  cache:
    cache-names: vms,qos
  host: ${HOST}
  application:
    name: eduVirt
  jpa:
    open-in-view: false
  profiles:
    active: @spring.profiles.active@
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    sender: ${MAIL_SENDER}
    protocol: ${MAIL_PROTOCOL:smtp}
    properties:
      "mail.smtp.auth": ${MAIL_PROPERTIES_ENABLE_AUTH:true}
      "mail.smtp.starttls.enable": ${MAIL_PROPERTIES_STARTTLS:true}
      "mail.smtp.ssl.enable": ${MAIL_PROPERTIES_SSL_ENABLE:true}
      "mail.smtp.ssl.trust": ${MAIL_PROPERTIES_SSL_TRUST:${HOST}}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
  datasource:
    url: ${EDUVIRT_DB_URL}
    username: ${EDUVIRT_DB_USERNAME}
    password: ${EDUVIRT_DB_PASSWORD}
    driver-class-name: ${EDUVIRT_DB_DRIVER_CLASS:org.postgresql.Driver}
  liquibase:
    default-schema: public
    user: ${LIQUIBASE_USER}
    password: ${LIQUIBASE_PASSWORD}
    change-log: classpath:/config/liquibase/master.xml

ovirt:
  engine:
    url: ${ENGINE_URL}
    username: ${ENGINE_USERNAME}
    password: ${ENGINE_PASSWORD}
    jks:
      file: ${JKS_FILE:ovirte-tst-keystore.jks}
      password: ${JKS_PASSWORD:password}

#auth:
#  keycloack:
#    tokenUri: ${KEYCLOAK_TOKEN_URI}
#    url: ${KEYCLOAK_URL}
#    clientId: ${KEYCLOAK_CLIENT_ID}
#    clientSecret: ${KEYCLOAK_CLIENT_SECRET}
#    redirectUri: ${KEYCLOAK_REDIRECT_URI}

auth:
  keycloack:
    loginUrl: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/${KEYCLOAK_PROTOCOL}/auth
    logoutUrl: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/${KEYCLOAK_PROTOCOL}/logout
    loginRedirectUrl: ${KEYCLOAK_REDIRECT_LOGIN_URI}
    logoutRedirectUrl: ${KEYCLOAK_REDIRECT_LOGOUT_URI}
    clientId: ${KEYCLOAK_CLIENT_ID}
    tokenUrl: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/${KEYCLOAK_PROTOCOL}/token
    clientSecret: ${KEYCLOAK_CLIENT_SECRET}

mail:
  default:
    timezone: ${DEFAULT_MAIL_TIMEZONE:CET}
    language: ${DEFAULT_MAIL_LANGUAGE:pl}

frontend:
  login: ${FRONTEND_LOGIN}
  callback: ${FRONTEND_CALLBACK}

maintenance-interval:
  min-ahead: ${MAINTENANCE_INTERVAL_MIN_AHEAD}

window:
  length: ${RESERVATION_WINDOW_LENGTH:15}

resource:
  warning:
    mail: ${RESOURCE_WARNING_MAILS_ENABLED:true}

jws:
  secret: ${JWS_SECRET}

executor:
  task-time-tolerance: ${EXECUTOR_TASK_TIME_TOLERANCE:3}
  vm:
    grace-time: ${EXECUTOR_VM_SHUTDOWN_GRACE_TIME:2}
  mail:
    urls:
      reservations: ${FRONTEND_RESERVATIONS_VIEW:http://localhost:5173/reservations}
