spring:
  sql:
    init:
      mode: never
  jpa:
    show-sql: false
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
