spring:
  host: ${HOST}
  application:
    name: eduVirt
  jpa:
    open-in-view: false
  h2:
    console:
      enabled: true
  config:
    import: optional:classpath:ovirt.yaml,optional:classpath:postgres-db.yaml
  profiles:
    active: @spring.profiles.active@

jdbc:
  eduvirt:
    driver-class-name: ${DB_DRIVER_CLASS}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    jdbcUrl: ${DB_URL}
#    maximum-pool-size: 5
#    maxWaitMillis: 40000

auth:
  secret-key: ${AUTH_SECRET_KEY}
  expiration-hours: ${AUTH_EXPIRATION_HOURS}
  keycloack:
    tokenUri: ${KEYCLOAK_TOKEN_URI}
    url: ${KEYCLOAK_URL}
    clientId: ${KEYCLOAK_CLIENT_ID}
    clientSecret: ${KEYCLOAK_CLIENT_SECRET}
    redirectUri: ${KEYCLOAK_REDIRECT_URI}
