spring:
  host: ${HOST}
  application:
    name: eduVirt
  jpa:
    open-in-view: false
  profiles:
    active: @spring.profiles.active@
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    sender: ${MAIL_SENDER}
    protocol: ${MAIL_PROTOCOL}
    properties:
      "mail.smtp.auth": ${MAIL_PROPERTIES_ENABLE_AUTH}
      "mail.smtp.starttls.enable": ${MAIL_PROPERTIES_STARTTLS}
      "mail.smtp.ssl.enable": ${MAIL_PROPERTIES_SSL_ENABLE}
      "mail.smtp.ssl.trust": ${MAIL_PROPERTIES_SSL_TRUST}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
  datasource:
    url: ${EDUVIRT_DB_URL}
    username: ${EDUVIRT_DB_USERNAME}
    password: ${EDUVIRT_DB_PASSWORD}
    driver-class-name: ${EDUVIRT_DB_DRIVER_CLASS}

ovirt:
  engine:
    url: ${ENGINE_URL}
    username: ${ENGINE_USERNAME}
    password: ${ENGINE_PASSWORD}
    jks:
      file: ${JKS_FILE}
      password: ${JKS_PASSWORD}

auth:

  keycloack:
    tokenUri: ${KEYCLOAK_TOKEN_URI}
    url: ${KEYCLOAK_URL}
    clientId: ${KEYCLOAK_CLIENT_ID}
    clientSecret: ${KEYCLOAK_CLIENT_SECRET}
    redirectUri: ${KEYCLOAK_REDIRECT_URI}
