services:
  db-eduvirt:
    image: postgres:16.4-alpine
    container_name: postgres-eduvirt
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: p@ssw0rd
    ports:
      - "5432:5432"
